image: cirrusci/flutter:1.22.4

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/android/.gradle
- mkdir -p ${GRADLE_USER_HOME}
- echo ${GRADLE_PROPS} | base64 -d > ${GRADLE_USER_HOME}/gradle.properties
- chmod +x android/gradlew

after_script:
- rm -f ${GRADLE_USER_HOME}/gradle.properties

build-debug:
  stage: build
  only:
    - branches
  script:
    - flutter channel stable
    - flutter upgrade
    - flutter pub get
    - flutter build appbundle --debug
